### ISSUE TITLE
Display Phorum

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#120]
- [x] Figure out HTML rendering / rendering of the `<br />` tag
- [x] CSS
- [x] Alter model and add relation to user profile where applicable
- [x] User Star
- [x] User Icon
- [x] Adding a comment
- [x] Deleting a comment
- [x] Fix User Star [Comment](https://github.com/dracidoupe/graveyard/issues/120#issuecomment-810168604)

**Comment by jimmeak** [comment]
What would be the best way how to delete comments? Make in view.py new delete_phorum_comment action or somehow manage that in action through some optional delete_id that would be default null?

**Comment by Almad** [comment]
`Comment.objects.delete(pk=id, user_id=request.user.pk)`? :)

**Comment by Almad** [comment]
[Django docs](https://docs.djangoproject.com/en/3.1/ref/models/querysets/#django.db.models.query.QuerySet.delete)

**Comment by jimmeak** [comment]
I believe you did not get the point. The point is where should the link reference to. Or you can do the same as in javascript <a .... action="Comment.objects....."? Cause I don't see anything like that in the docs.

**Comment by Almad** [comment]
I'm not sure what you're asking about—let's discuss on the call in the evening

**Comment by jimmeak** [comment]
New problem - icons looks bad when "Smazat" is present. It needs fix (I am adding this into the list of this ticket)
![image](https://user-images.githubusercontent.com/21171948/112986202-825e3780-9161-11eb-8545-d4671769f694.png)

**Comment by jimmeak** [comment]
I am clonsing this issue, since it has been already moved to Done in 2021
