### ISSUE TITLE
Some creative pages destroy the layout

### ISSUE THREAD

**Issue by jimmeak** [dracidoupe/graveyard#144]
Going to the section "Hraničářská kouzla" and then click on "předchozí" few times gets us to the spell in the attempted image.

[http://nove.dracidoupe.cz/rubriky/hranicarkouzla/?z_s=3](http://nove.dracidoupe.cz/rubriky/hranicarkouzla/?z_s=3)

I did not find any more ranger spells with this behavior, there must be some difference between this spell and others - first part of this issue is to look for it. 

- [ ] Find difference between this spell and others (or different reason why this is happening)
- [ ] Fix the spell out of it. :) 

![image](https://user-images.githubusercontent.com/21171948/111029595-ccbf8480-83fd-11eb-9a05-aac85b09aed4.png)

**Comment by Almad** [comment]
I think this got fixed by the combination of our dear editors fixing HTML & our migration to grid layout.
