### ISSUE TITLE
Migrate skins to grid layout

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#152]
Flex causes problems and is slower anyway. 

See [MDN Guide](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)

**Comment by jimmeak** [comment]
@Wynnka Here we have some goals we should do. 
- [ ] Create grid layout
- [ ] Create multiskin support (public.html + static/css structure)
- [ ] Adjust the light skin
- [ ] Adjust the dark skin

**Comment by jimmeak** [comment]
Both skins migrated, also historic skin added

**Comment by Almad** [comment]
Great job! <3
