### ISSUE TITLE
Pages: Creators and Moderators

### ISSUE THREAD

**Issue by jimmeak** [dracidoupe/graveyard#175]
[Original site](http://www.dracidoupe.cz/index.php?rub=credits&skin=dark)

Maybe think of new design.

**Comment by jimmeak** [comment]
@Almad Is this a pure static html site or does this pull data from db?

**Comment by Almad** [comment]
half-static (hall of fame), half-dynamic from db (editors)

**Comment by Almad** [comment]
Partially fixed by #330, partially superseded by #332 (can wait until phase II if necessary)
