### ISSUE TITLE
Reseting skin after logout

### ISSUE THREAD

**Issue by jimmeak** [dracidoupe/graveyard#187]
If someone tries to log out of the app, the skin will automatically changed to light. It should stay the same.

I am not sure of the reason - I guess the skin is saved in session file and after log out this file is completely deleted.

**Comment by Almad** [comment]
Agreed, this is weird and not sure why it's happening either. 

It touches on another topic though, not sure if I wouldn't like to keep doupe cookieless, but let me think about it.
