### ISSUE TITLE
Font for historic

### ISSUE THREAD

**Issue by jimmeak** [dracidoupe/graveyard#188]
Historic use to have the font "Papyrus" but it has been all developed via images.

We can try to create something similar to papyrus with CSS and some fonts. Following links can be useful.

[Font Design](https://css-tricks.com/how-to-do-knockout-text/)
[Generating random background](https://blog.logrocket.com/how-to-create-randomly-generated-backgrounds-with-the-css-paint-api/)

**Comment by Almad** [comment]
Yeah, I think it would be great if we could use something open source.

I'd be happy to buy Papyrus to produce images, but I think it violates Papyrus ToS, even though nobody will probably bother.

**Comment by jimmeak** [comment]
I think this should be closed now since we have neohistoric and I think no need to do original historic.
