### ISSUE TITLE
Track the login time

### ISSUE THREAD

**Issue by jimmeak** [dracidoupe/graveyard#217]
When a user signs in, the column "pospristup" should notice it.

**Comment by Almad** [comment]
I'd say it's not a bug, but interop issue 😏

**Comment by Almad** [comment]
@jimmeak could you please get rid of the warning? 

`/Users/almad/Documents/projects/graveyard/gvenv/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1538: RuntimeWarning: DateTimeField UserProfile.last_login received a naive datetime (2021-06-16 16:54:32.324808) while time zone support is active.
  warnings.warn(
```
