### ISSUE TITLE
Investigate different linebreaks in Dating

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#280]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/44565/121184321-4502de00-c865-11eb-9f57-66102bb7f600.png">

(new)

vs

<img width="642" alt="image" src="https://user-images.githubusercontent.com/44565/121184604-8c896a00-c865-11eb-8628-e77644d319bf.png">

(old/original)

**Comment by jimmeak** [comment]
At larger screen this particular dating item is the same. Is it possible you already fixed it @Almad ?

**Comment by Almad** [comment]
It looks fixed indeed! 

But it also makes me think that maybe we should add `hyphens: auto` to the articles, but that's unrelated :)
