### ISSUE TITLE
Changing skin takes you away from the page you are at

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#38]
* Add `returnto` argument to `http://nove.dracidoupe.cz/nastaveni/zmena-skinu/?skin=light`
* Do not forget to validate it's on the same server to prevent redirect hijacking

**Comment by jimmeak** [comment]
Redirect to existing pages is done.

To do: Fix validation of given redirect path.
![image](https://user-images.githubusercontent.com/21171948/109425950-35186a00-79eb-11eb-80ca-3720921d7c67.png)

**Comment by Almad** [comment]
Fixed by #139
