### ISSUE TITLE
Handle creations without authors properly

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#43]
(originally, there are creations with sources (zdroje) without authors)

**Comment by Almad** [comment]
I _think_ this is done. 

@Nathaka Could you please verify? Look into some old creations and see whether they are handled properly

**Comment by Nathaka** [comment]
> I _think_ this is done.
> 
> @Nathaka Could you please verify? Look into some old creations and see whether they are handled properly

What is "handled properly"? There are still articles with no author, but if you assigned those I found in #191 I don't see what else is there to check

**Comment by Almad** [comment]
Those were creations assigned to no author or source or to the author without nick. 

What I meant is those that are copied from a site, that they don't explode. But it seems it works: 

http://nove.dracidoupe.cz/rubriky/bestiar/30-mongo/
http://nove.dracidoupe.cz/autor/3218-http-www-volny-cz-sikmar/

I "just" see the duplicate authors there

**Comment by Nathaka** [comment]
@Almad Sorry, didn't understand you at first. At least I can confirm it works great now (much better than on the old version even).
