### ISSUE TITLE
Translate model attributes in English

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#54]
This can be done without db migration since db column can be overruled. It will make codebase more consistent and readable. 

- [x] Tavern @Almad 
- [x] News @Almad 
- [x] Creations @Almad 
- [x] Discussion @Almad  
- [x] Social @Almad 
- [x] Users @Almad 

## Fuckup recovery

- [x] Save original branch for easy final version copypasting
- [x] Squash original translation blob
- [x] Copypaste back all original column names
- [x] Create `db_column` AlterColumn migrations
- [x] Copy all models from the original final branch
- [x] `yes | rename migrations`
- [x] Verify tests 😬

**Comment by jimmeak** [comment]
Some todos to discuss on 2021-02-28
