### ISSUE TITLE
Display local times correctly

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#57]
See [Czech typography rules](https://prirucka.ujc.cas.cz/?id=820). I'd also argue:

* For articles, doesn't make sense to display seconds (maybe not even hours/minutes?)
* It does so for comments, chats etc. 

This should be unified at all places

**Comment by jimmeak** [comment]
Write a filter https://docs.djangoproject.com/en/3.1/howto/custom-template-tags/
