### ISSUE TITLE
Add proper favicon

### ISSUE THREAD

**Issue by Almad** [dracidoupe/graveyard#69]
Fix dragon & store as ico. Sources:

* https://github.com/dracidoupe/graveyard/blob/master/static/skins/dark/img/drak.svg
* https://github.com/dracidoupe/graveyard/blob/master/static/skins/light/img/drak.svg

**Comment by Wynnka** [comment]
@jimmeak
Star wars - level 2: There are missing 4 items for Dark skin, 3 items for Historic and 3 L
![image](https://user-images.githubusercontent.com/75934655/115033955-48b05f00-9ecb-11eb-866d-9f230af56bd7.png)
